import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {MemoryStorage,loadImporter,loadTrainingModules} from './helpers.mjs';
import {longFormRows,workbookFromLongFormRows} from './fixtures/long-form-daily-fixture.mjs';

function parsed(){return loadImporter().parseLongFormDailyGrid(longFormRows,{fileName:'匿名测试.xlsx',sheetName:'手机查看版_一日一格'});}

test('L1. 严格识别 Long-form Daily Grid',()=>{const app=loadImporter();assert.equal(app.detectLongFormDailyGrid(longFormRows,'手机查看版_一日一格'),true);});
test('L2. Section heading 通用解析元数据',()=>{const h=loadImporter().parseSectionHeading('主项热身｜约8–10分钟；不计有效组');assert.equal(h.sectionType,'warmup');assert.equal(h.durationMin,8);assert.equal(h.durationMax,10);assert.equal(h.countsAsWorkingSets,false);});
test('L3. RIR 箭头是逐组序列，范围不是序列',()=>{const app=loadImporter();assert.deepEqual(Array.from(app.parseSetSequence('2→1→1',3),x=>[x.min,x.max]),[[2,2],[1,1],[1,1]]);assert.equal(app.parseSetSequence('1–2',2),null);});
test('L4. 匿名黄金 fixture 生成 10 个稳定 Workout',()=>{const result=parsed();assert.equal(result.plan.length,10);assert.equal(new Set(result.plan.map(x=>x.sourceWorkoutKey)).size,10);assert.equal(result.plan[0].sourceWorkoutKey,'longform:row:001');assert.equal(result.plan[8].cycleDay,'D5');});
test('L5. D1 热身、主训练、技术提示、基本功完整',()=>{const d=parsed().plan[0];assert.equal(d.activities[0].warmupType,'ramp');assert.equal(d.exercises[0].techniqueCue,'保持稳定轨迹。');assert.equal(d.exercises.filter(x=>x.trainingRole==='skill-retention').length,2);assert.equal(d.exercises.at(-1).countsAsHypertrophySet,false);});
test('L6. D2 超级组保留独立 Exercise 和规则',()=>{const d=parsed().plan[1];assert.equal(d.supersetRules.length,1);assert.equal(d.supersetRules[0].mode,'alternating');assert.equal(d.supersetRules[0].members.length,2);assert.equal(d.supersetRules[0].transitionMinSec,10);assert.equal(d.supersetRules[0].roundRestMaxSec,120);assert.ok(d.exercises.some(x=>x.perSide));});
test('L7. 有氧使用时间和 RPE，不变成 reps',()=>{const cardio=parsed().plan[1].activities.find(x=>x.activityType==='cardio');assert.equal(cardio.durationMinSec,1200);assert.equal(cardio.durationMaxSec,1800);assert.equal(cardio.rpeMin,3);assert.deepEqual(Array.from(cardio.modalityOptions),['单车','椭圆机']);});
test('L8. 完全休息不生成 Exercise 或 Activity',()=>{const d=parsed().plan[2];assert.equal(d.workoutType,'rest');assert.equal(d.exercises.length,0);assert.equal(d.activities.length,0);assert.ok(d.instructions.some(x=>x.category==='recovery-check'));});
test('L9. 攀岩是 Activity 并保留 drills',()=>{const d=parsed().plan[3],climb=d.activities.find(x=>x.activityType==='climbing');assert.ok(climb);assert.equal(climb.durationMinSec,2700);assert.equal(climb.drills.length,2);assert.equal(d.exercises.some(x=>x.name==='示例脚法'),false);});
test('L10. 逐组 RIR 正确生成 Set Prescription',()=>{const ex=parsed().plan[4].exercises.find(x=>x.name==='绳索示例外展');assert.deepEqual(Array.from(ex.sets.slice(0,3),x=>x.targetRirMin),[2,1,1]);});
test('L11. 末组双递减是同一 Exercise 的多阶段第四组',()=>{const ex=parsed().plan[4].exercises.find(x=>x.hasMultiStageSet),drop=ex.sets[3];assert.equal(ex.sets.length,4);assert.equal(drop.setType,'dropset');assert.equal(drop.segments.length,3);assert.deepEqual([drop.segments[1].loadAdjustmentMin,drop.segments[1].loadAdjustmentMax],[-25,-20]);assert.deepEqual([drop.segments[1].transitionMinSec,drop.segments[1].transitionMaxSec],[10,15]);});
test('L12. 超级组 A/B 不交叉',()=>{const d=parsed().plan[4];assert.equal(d.supersetRules.length,2);assert.notEqual(d.supersetRules[0].supersetId,d.supersetRules[1].supersetId);assert.equal(new Set(d.supersetRules.flatMap(x=>x.members)).size,4);});
test('L13. measureUnit 支持 meters 和 seconds',()=>{const d=parsed().plan[5],walk=d.exercises.find(x=>x.measureUnit==='meters'),hold=d.exercises.find(x=>x.measureUnit==='seconds');assert.equal(walk.perSide,true);assert.equal(walk.repsMin,30);assert.equal(hold.repsMin,20);});
test('L14. 语义损失为 0',()=>{const result=parsed();assert.equal(result.semanticStats.unrecognizedBlocks,0);assert.deepEqual(Array.from(result.semanticWarnings),[]);assert.equal(result.validation.valid,true);});
test('L15. 原文使用共享块引用，能够无损重建',()=>{const result=parsed(),d=result.plan[0],source=d.sourceBlockIds.map(id=>result.sharedSourceBlocks[id]).join('\n');assert.match(source,/【主训练】/);assert.match(source,/【记录】记录示例数据/);assert.ok(Object.keys(result.sharedSourceBlocks).length<result.plan.reduce((n,x)=>n+x.sourceBlockIds.length,0));});
test('L16. importer 路由优先进入 Long-form，不触发 Legacy',()=>{const result=loadImporter().parseWorkbookToImport(workbookFromLongFormRows(),{name:'匿名测试.xlsx'});assert.equal(result.format,'long-form-daily-v1');assert.equal(result.plan.length,10);});
test('L17. 旧 Legacy 一日一格不会被新 adapter 抢走',()=>{const app=loadImporter(),rows=[['顺序日','周次','周内日','类型','主题','今日内容（整格照做）','完成日期/备注'],[1,1,'周一','训练日','旧格式','【功能/热身】\n踝活动 2组×10次\n【主训练】\n深蹲｜3组×5次｜余力3｜休180秒','']];assert.equal(app.detectLongFormDailyGrid(rows,'手机查看版_一日一格'),false);assert.notEqual(app.parseDailyGridSheet(rows,{id:'legacy'}).format,'long-form-daily-v1');});
test('L18. Schema v6 normalize 保留新增语义与稳定 ID',()=>{const app=loadTrainingModules(),result=parsed(),program=app.createProgramFromPlan(result.plan,{name:'匿名',source:'long-form-daily-v1'});const ex=program.days[4].exercises.find(x=>x.hasMultiStageSet);assert.equal(program.days[0].activities[0].warmupType,'ramp');assert.equal(ex.sets[3].segments.length,3);assert.equal(ex.exerciseId,'longform:row:005:exercise:02');});
test('L19. 执行页支持每组 multi-stage，而不是整张卡强制递减',()=>{const source=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.match(source,/compoundSpecFromSetPlan\(savedSet\)\|\|compound/);assert.match(source,/含多阶段递减组/);});
test('L20. Round-trip semantic validator 校验身份和引用完整性',()=>{const app=loadImporter(),result=parsed(),report=app.validateLongFormProgram(result.plan,{sharedSourceBlocks:result.sharedSourceBlocks,unrecognized:[]});assert.equal(report.valid,true);assert.deepEqual(Array.from(report.errors),[]);const broken=JSON.parse(JSON.stringify(result.plan));broken[0].sourceWorkoutKey=broken[1].sourceWorkoutKey;assert.equal(app.validateLongFormProgram(broken,{sharedSourceBlocks:result.sharedSourceBlocks}).valid,false);});
test('L21. 多阶段组使用自己的休息处方，不继承普通组',()=>{const source=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.match(source,/restRangeForSetPlan\(rr,savedSet/);const drop=parsed().plan[4].exercises.find(x=>x.hasMultiStageSet).sets[3];assert.deepEqual([drop.targetRestMin,drop.targetRestMax],[90,120]);});
test('L22. 执行页显示独立 Superset Sequence',()=>{const source=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.match(source,/supersetSequences/);assert.match(source,/members\.join\(' → '\)/);});
test('L23. Long-form Preview 显示完整语义统计和 validation',()=>{const app=loadImporter(),text=app.importPrecheckText({format:'long-form-daily-v1',plan:[{workoutId:'W1'}],semanticStats:{workouts:96,types:{'力量训练':18,'力量＋有氧':18,'完全休息':24,'攀岩':18,'减载训练':12,'减载攀岩':6},formalExercises:360,warmups:72,skillRetention:228,supersetGroups:48,multiStageDropSets:9,cardio:24,climbing:36,unrecognizedBlocks:0},semanticWarnings:[],validation:{valid:true,errors:[],warnings:[]}},'匿名计划.xlsx');for(const expected of ['Workout：96','力量训练：18','力量＋有氧：18','完全休息：24','攀岩：18','减载训练：12','减载攀岩：6','正式动作：360','热身模块：72','技能保留动作：228','超级组：48','多阶段递减组：9','有氧活动：24','攀岩活动：36','未识别内容块：0','validation：0 errors / 0 warnings'])assert.match(text,new RegExp(expected));});
test('L24. 容量预估只读并显示 Program、ROOT 和导入后体积',()=>{const raw=JSON.stringify({schemaVersion:6,payload:'x'.repeat(1200)}),storage=new MemoryStorage({'training-tracker-state':raw}),app=loadImporter(storage),result=parsed(),before=storage.getItem('training-tracker-state'),estimate=app.estimateImportStorage(result),text=app.importPrecheckText(result,'匿名计划.xlsx');assert.ok(estimate.programBytes>0);assert.equal(estimate.currentRootBytes,new TextEncoder().encode(raw).length);assert.equal(estimate.estimatedAfterBytes,estimate.currentRootBytes+estimate.programBytes);assert.match(text,/预计 Program 大小：约/);assert.match(text,/当前 ROOT：约/);assert.match(text,/导入后预计：约/);assert.equal(storage.getItem('training-tracker-state'),before);});
